apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <%= @pvc_name %>
  annotations:
    volume.alpha.kubernetes.io/storage-class: "bar"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
