apiVersion: v1
kind: Pod
metadata:
  name: <%= @pod_name %>
  labels:
    name: <%= @pod_name %>
spec:
  restartPolicy: Never
  containers:
    - name: <%= @pod_name %>
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/etc/foo"
        readOnly: true
        name: secret-vol
  volumes:
      - name: secret-vol
        secret:
          secretName: <%= @secret %>
